<?php

/**
 * @file
 * Installation file for the commerce_order_simple_cleanup module.
 */

function commerce_order_simple_cleanup_enable() {
  drupal_set_message(t('Commerce Order Simple Cleanup has been installed. You may now configure it <a href="/admin/commerce/config/commerce-order-simple-cleanup">here</a>.'));
}

/**
 * Implements hook_uninstall().
 *
 * @todo Delete all the variables set.
 *
 * @see commerce_order_simple_cleanup_admin_form
 *
 */
function commerce_order_simple_cleanup_uninstall() {
  variable_del('commerce_order_simple_cleanup_status');
  variable_del('commerce_order_simple_cleanup_time');
  variable_del('commerce_order_simple_cleanup_limit');
}